--
-- PostgreSQL database dump
--

\restrict ug6I3ug6rxMhUydtsCWQsBOGzSgmz35mMwj35ZIedjdP8sDEeCzdK8R9iMqEVbJ

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games (
    id bigint NOT NULL,
    game_name character varying(30) NOT NULL,
    play_mode character varying(20) NOT NULL,
    difficulty integer,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT games_game_name_check CHECK (((game_name)::text = ANY ((ARRAY['EYEFIGHT'::character varying, 'BLINK'::character varying, 'DRAWING'::character varying, 'RHYTHM'::character varying, 'HOCKEY'::character varying])::text[]))),
    CONSTRAINT games_play_mode_check CHECK (((play_mode)::text = ANY ((ARRAY['SOLO'::character varying, 'INVITE'::character varying, 'RANDOM'::character varying, 'AI'::character varying])::text[])))
);


--
-- Name: games_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: games_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.games_results (
    id bigint NOT NULL,
    play_id uuid NOT NULL,
    game_id bigint NOT NULL,
    game_result jsonb NOT NULL,
    started_at timestamp with time zone NOT NULL,
    ended_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: games_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.games_results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_comments (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    content character varying(200) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: group_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_members (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role character varying(20) NOT NULL,
    joined_at timestamp with time zone NOT NULL,
    CONSTRAINT group_members_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MEMBER'::character varying])::text[])))
);


--
-- Name: group_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: group_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.group_posts (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    content character varying(500) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


--
-- Name: group_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.group_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.group_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: groups_; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.groups_ (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(255),
    group_code character varying(6) NOT NULL,
    owner_user_id bigint NOT NULL,
    visibility character varying(20) NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT groups_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: groups__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.groups_ ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: participants_; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.participants_ (
    id bigint NOT NULL,
    result_id bigint NOT NULL,
    user_id bigint,
    participant_type character varying(20) NOT NULL,
    slot_no integer NOT NULL,
    outcome character varying(20) NOT NULL,
    rank_no integer,
    display_name character varying(50),
    score bigint,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT participants_outcome_check CHECK (((outcome)::text = ANY ((ARRAY['WIN'::character varying, 'LOSE'::character varying, 'DRAW'::character varying, 'FORFEIT'::character varying, 'COMPLETED'::character varying])::text[]))),
    CONSTRAINT participants_type_check CHECK (((participant_type)::text = ANY ((ARRAY['USER'::character varying, 'GUEST'::character varying, 'AI'::character varying])::text[])))
);


--
-- Name: participants__id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.participants_ ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participants__id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ranking_trends; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ranking_trends (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    game_name character varying(20) NOT NULL,
    week_start date NOT NULL,
    last_rank integer NOT NULL,
    trend character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT ranking_trends_game_name_check CHECK (((game_name)::text = ANY ((ARRAY['EYEFIGHT'::character varying, 'BLINK'::character varying, 'DRAWING'::character varying, 'RHYTHM'::character varying, 'HOCKEY'::character varying])::text[]))),
    CONSTRAINT ranking_trends_trend_check CHECK (((trend)::text = ANY ((ARRAY['UP'::character varying, 'DOWN'::character varying, 'SAME'::character varying])::text[])))
);


--
-- Name: ranking_trends_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ranking_trends ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ranking_trends_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_accounts (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(20) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT social_accounts_provider_check CHECK (((provider)::text = 'KAKAO'::text))
);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.social_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    nickname character varying(50) NOT NULL,
    password character varying(255),
    profile_img_code character varying(20) NOT NULL,
    deleted_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT users_profile_img_code_check CHECK (((profile_img_code)::text = ANY ((ARRAY['PROFILE_1'::character varying, 'PROFILE_2'::character varying, 'PROFILE_3'::character varying, 'PROFILE_4'::character varying, 'PROFILE_5'::character varying, 'PROFILE_6'::character varying, 'PROFILE_7'::character varying, 'PROFILE_8'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.games (id, game_name, play_mode, difficulty, created_at, updated_at) FROM stdin;
1	HOCKEY	INVITE	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
2	HOCKEY	RANDOM	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
3	HOCKEY	AI	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
4	EYEFIGHT	SOLO	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
5	EYEFIGHT	INVITE	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
6	EYEFIGHT	RANDOM	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
7	DRAWING	AI	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
8	RHYTHM	SOLO	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
9	RHYTHM	INVITE	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
10	RHYTHM	RANDOM	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
11	BLINK	SOLO	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
12	BLINK	INVITE	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
13	BLINK	RANDOM	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
\.


--
-- Data for Name: games_results; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.games_results (id, play_id, game_id, game_result, started_at, ended_at, created_at, updated_at) FROM stdin;
1	11111111-1111-1111-1111-111111111111	11	{"mode": "SOLO", "slots": [{"score": 53, "slotNo": 1, "userId": 2, "outcome": "COMPLETED"}]}	2026-08-05 14:00:00+00	2026-08-05 14:01:00+00	2026-08-05 14:01:00+00	2026-08-05 14:01:00+00
2	22222222-2222-2222-2222-222222222222	1	{"mode": "INVITE", "slots": [{"score": 5, "slotNo": 1, "userId": 4, "outcome": "WIN"}, {"score": 3, "slotNo": 2, "userId": 3, "outcome": "LOSE"}]}	2026-08-05 15:00:00+00	2026-08-05 15:03:00+00	2026-08-05 15:03:00+00	2026-08-05 15:03:00+00
3	33333333-3333-3333-3333-333333333333	8	{"mode": "SOLO", "slots": [{"score": 120, "slotNo": 1, "userId": 2, "outcome": "COMPLETED"}]}	2026-08-05 16:00:00+00	2026-08-05 16:01:30+00	2026-08-05 16:01:30+00	2026-08-05 16:01:30+00
4	44444444-4444-4444-4444-444444444444	7	{"mode": "AI", "slots": [{"score": 88, "slotNo": 1, "userId": 5, "outcome": "WIN"}, {"type": "AI", "score": 70, "slotNo": 2, "userId": null, "outcome": "LOSE"}]}	2026-08-05 17:00:00+00	2026-08-05 17:02:00+00	2026-08-05 17:02:00+00	2026-08-05 17:02:00+00
\.


--
-- Data for Name: group_comments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.group_comments (id, post_id, author_user_id, content, created_at, updated_at) FROM stdin;
1	1	4	오 축하해요! 저도 도전할게요.	2026-08-05 12:10:00+00	2026-08-05 12:10:00+00
2	1	1	같이 한 판 해요 ㅎㅎ	2026-08-05 12:15:00+00	2026-08-05 12:15:00+00
3	2	5	감사합니다, 덕분에 랭킹 올랐어요!	2026-08-05 14:00:00+00	2026-08-05 14:00:00+00
\.


--
-- Data for Name: group_members; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.group_members (id, group_id, user_id, role, joined_at) FROM stdin;
1	1	1	OWNER	2026-08-03 08:00:00+00
2	1	4	MEMBER	2026-08-03 10:12:00+00
3	2	2	OWNER	2026-08-04 09:30:00+00
4	2	5	MEMBER	2026-08-04 11:00:00+00
\.


--
-- Data for Name: group_posts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.group_posts (id, group_id, author_user_id, content, created_at, updated_at) FROM stdin;
1	1	1	오늘 눈싸움 신기록 세웠어요! 다들 도전해봐요.	2026-08-05 12:00:00+00	2026-08-05 12:00:00+00
2	2	2	리듬게임 박자 놓치지 않는 팁 공유합니다.	2026-08-05 13:30:00+00	2026-08-05 13:30:00+00
\.


--
-- Data for Name: groups_; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.groups_ (id, name, description, group_code, owner_user_id, visibility, capacity, created_at, updated_at) FROM stdin;
1	새벽 눈운동 모임	집중 사이 눈으로 리프레시하는 사람들	AB12CD	1	PUBLIC	10	2026-08-03 08:00:00+00	2026-08-03 08:00:00+00
2	깜빡이 고수들	눈 깜빡이기 랭킹 노리는 방	XY99ZZ	2	PRIVATE	5	2026-08-04 09:30:00+00	2026-08-04 09:30:00+00
\.


--
-- Data for Name: participants_; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.participants_ (id, result_id, user_id, participant_type, slot_no, outcome, rank_no, display_name, score, created_at, updated_at) FROM stdin;
1	1	2	USER	1	COMPLETED	1	깜빡이장인	53	2026-08-05 14:01:00+00	2026-08-05 14:01:00+00
2	2	4	USER	1	WIN	1	아이하키왕	5	2026-08-05 15:03:00+00	2026-08-05 15:03:00+00
3	2	3	USER	2	LOSE	2	카카오철수	3	2026-08-05 15:03:00+00	2026-08-05 15:03:00+00
4	3	2	USER	1	COMPLETED	1	깜빡이장인	120	2026-08-05 16:01:30+00	2026-08-05 16:01:30+00
5	4	5	USER	1	WIN	1	눈으로그리는화가	88	2026-08-05 17:02:00+00	2026-08-05 17:02:00+00
6	4	\N	AI	2	LOSE	2	AI	70	2026-08-05 17:02:00+00	2026-08-05 17:02:00+00
\.


--
-- Data for Name: ranking_trends; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ranking_trends (id, user_id, game_name, week_start, last_rank, trend, created_at, updated_at) FROM stdin;
1	2	BLINK	2026-08-03	1	UP	2026-08-05 14:01:00+00	2026-08-05 14:01:00+00
2	4	HOCKEY	2026-08-03	1	SAME	2026-08-05 15:03:00+00	2026-08-05 15:03:00+00
3	2	RHYTHM	2026-08-03	2	DOWN	2026-08-05 16:01:30+00	2026-08-05 16:01:30+00
4	5	DRAWING	2026-08-03	1	UP	2026-08-05 17:02:00+00	2026-08-05 17:02:00+00
\.


--
-- Data for Name: social_accounts; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.social_accounts (id, user_id, provider, provider_user_id, created_at) FROM stdin;
1	3	KAKAO	3948572610	2026-08-02 11:30:00+00
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, email, nickname, password, profile_img_code, deleted_at, created_at, updated_at) FROM stdin;
1	admin@eyedontcare.shop	눈대장	{bcrypt}$2a$10$DUMMYHASHadminxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	PROFILE_1	\N	2026-08-01 09:00:00+00	2026-08-01 09:00:00+00
2	blinker@eyedontcare.shop	깜빡이장인	{bcrypt}$2a$10$DUMMYHASHblinkerxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	PROFILE_2	\N	2026-08-01 10:15:00+00	2026-08-05 14:20:00+00
3	\N	카카오철수	\N	PROFILE_3	\N	2026-08-02 11:30:00+00	2026-08-02 11:30:00+00
4	hockey@eyedontcare.shop	아이하키왕	{bcrypt}$2a$10$DUMMYHASHhockeyxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	PROFILE_4	\N	2026-08-02 13:00:00+00	2026-08-02 13:00:00+00
5	draw@eyedontcare.shop	눈으로그리는화가	{bcrypt}$2a$10$DUMMYHASHdrawxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx	PROFILE_5	\N	2026-08-03 15:45:00+00	2026-08-03 15:45:00+00
6	\N	withdrawn-6	\N	PROFILE_1	2026-08-04 18:00:00+00	2026-08-03 16:00:00+00	2026-08-04 18:00:00+00
\.


--
-- Name: games_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.games_id_seq', 13, true);


--
-- Name: games_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.games_results_id_seq', 4, true);


--
-- Name: group_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.group_comments_id_seq', 3, true);


--
-- Name: group_members_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.group_members_id_seq', 4, true);


--
-- Name: group_posts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.group_posts_id_seq', 2, true);


--
-- Name: groups__id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.groups__id_seq', 2, true);


--
-- Name: participants__id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.participants__id_seq', 6, true);


--
-- Name: ranking_trends_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ranking_trends_id_seq', 4, true);


--
-- Name: social_accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.social_accounts_id_seq', 1, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 6, true);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);


--
-- Name: games_results games_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games_results
    ADD CONSTRAINT games_results_pkey PRIMARY KEY (id);


--
-- Name: group_comments group_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_comments
    ADD CONSTRAINT group_comments_pkey PRIMARY KEY (id);


--
-- Name: group_members group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT group_members_pkey PRIMARY KEY (id);


--
-- Name: group_posts group_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_posts
    ADD CONSTRAINT group_posts_pkey PRIMARY KEY (id);


--
-- Name: groups_ groups__pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_
    ADD CONSTRAINT groups__pkey PRIMARY KEY (id);


--
-- Name: participants_ participants__pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participants_
    ADD CONSTRAINT participants__pkey PRIMARY KEY (id);


--
-- Name: ranking_trends ranking_trends_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ranking_trends
    ADD CONSTRAINT ranking_trends_pkey PRIMARY KEY (id);


--
-- Name: social_accounts social_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT social_accounts_pkey PRIMARY KEY (id);


--
-- Name: games uk_games_name_mode_difficulty; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT uk_games_name_mode_difficulty UNIQUE (game_name, play_mode, difficulty);


--
-- Name: games_results uk_games_results_play_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games_results
    ADD CONSTRAINT uk_games_results_play_id UNIQUE (play_id);


--
-- Name: group_members uk_group_members_group_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.group_members
    ADD CONSTRAINT uk_group_members_group_user UNIQUE (group_id, user_id);


--
-- Name: groups_ uk_groups_group_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.groups_
    ADD CONSTRAINT uk_groups_group_code UNIQUE (group_code);


--
-- Name: participants_ uk_participants_result_slot; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participants_
    ADD CONSTRAINT uk_participants_result_slot UNIQUE (result_id, slot_no);


--
-- Name: ranking_trends uk_ranking_trends_user_game_week; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ranking_trends
    ADD CONSTRAINT uk_ranking_trends_user_game_week UNIQUE (user_id, game_name, week_start);


--
-- Name: social_accounts uk_social_accounts_provider_identity; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT uk_social_accounts_provider_identity UNIQUE (provider, provider_user_id);


--
-- Name: social_accounts uk_social_accounts_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT uk_social_accounts_user UNIQUE (user_id);


--
-- Name: users uk_users_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_email UNIQUE (email);


--
-- Name: users uk_users_nickname; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_users_nickname UNIQUE (nickname);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: games_results fk_games_results_game; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.games_results
    ADD CONSTRAINT fk_games_results_game FOREIGN KEY (game_id) REFERENCES public.games(id);


--
-- Name: participants_ fk_participants_result; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.participants_
    ADD CONSTRAINT fk_participants_result FOREIGN KEY (result_id) REFERENCES public.games_results(id);


--
-- Name: social_accounts fk_social_accounts_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_accounts
    ADD CONSTRAINT fk_social_accounts_user FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict ug6I3ug6rxMhUydtsCWQsBOGzSgmz35mMwj35ZIedjdP8sDEeCzdK8R9iMqEVbJ

