FROM eclipse-temurin:25-jdk-alpine

WORKDIR /workspace

COPY gradlew gradlew
COPY gradle gradle
COPY build.gradle settings.gradle ./

RUN chmod +x gradlew && ./gradlew dependencies --no-daemon

COPY src src

EXPOSE 8080

CMD ["sh", "./gradlew", "bootRun", "--no-daemon"]
